language: java

jdk:
  - openjdk9
  - openjdk10
  - openjdk11
  
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION= 1.25.2

before_script:
  # Starts the containers in the background and leaves them running.
  - docker-compose -f docker/dev/docker-compose.yml up -d

script:
  - mvn clean install
  
after_success: 
  - mvn clean -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

after_script:
  # Stops running containers without removing them
  - docker-compose -f docker/dev/docker-compose.yml stop
  # Removes stopped service containers
  - docker-compose -f docker/dev/docker-compose.yml rm -f
  # Stops containers and removes containers, networks, volumes, and images created by up
  - docker-compose -f docker/dev/docker-compose.yml down
  
notifications:
  email: false